### PR TITLE
Refactor tasks_helper.py

### PR DESCRIPTION
**Pull request by albertliangcode**
Moved shared code block into a separate method.  New code block takes in a
course ID and returns all student users actively enrolled in the course.

### CODE REVIEW

**Comment by albertliangcode** [comment]
@kluo: Would you mind reviewing my code for me?

**Comment by albertliangcode** [comment]
@caesar2164 , would you be willing to review my code for me, please?

**Comment by caesar2164** [comment]
seems like a good change to me: :+1: 

@kluo, do you see any changes this needs?

**Comment by albertliangcode** [comment]
Thanks so much, @caesar2164 !

**Comment by kluo** [comment]
LGTM @albertliangcode @caesar2164 Although it's actually ading more lines of code than removing :P

**Comment by albertliangcode** [comment]
Okay!  I'll try to merge it!

**Pull request merged**
