### PR TITLE
Allow sneakpeek users to submit help modal tickets

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd & @kluo - using same conditional as other places where we treat sneakpeek as "unregistered"

### CODE REVIEW

**Comment by caesar2164** [comment]
working devstack:

screen shot 2016-08-17 at 2 19 06 pm

**Comment by stvstnfrd** [comment]
What was the behavior before?
We weren't asking for name/email?

**Comment by caesar2164** [comment]
not for sneakpeek, see trello card

**Comment by stvstnfrd** [comment]
+1

**Pull request merged**
