### PR TITLE
Fix long report name UI issue

### PR DESCRIPTION
**Pull request by kluo**
@stvstnfrd @caesar2164 

screen shot 2016-11-16 at 1 57 50 pm

### CODE REVIEW

**Comment by caesar2164** [comment]
Can we get a screenshot of what it looks like?

**Comment by caesar2164** [comment]
NICE 👍

**Comment by stvstnfrd** [comment]
+1

**Comment by stvstnfrd** [comment]
@kluo Don't forgot to kill your old branches, dude!

**Pull request merged**
