### PR TITLE
Remove anonymous users from subsection view count

### PR DESCRIPTION
**Pull request by tkim135**
@dcadams @stvstnfrd Management command edited to update subsection view count in instructor dashboard to exclude anonymous users.

For example, in the picture below, before the fix it used to say 2 students opened the subsection, and a username like "anon__h8104ht4g0rn" would appear.
screen shot 2018-08-29 at 11 31 15 am

CC: @saharm1

### CODE REVIEW

**Comment by dcadams** [comment]
Looks like this is going in the right direction. You could take a look at the tests and see if any should be affected by this change.

**Comment by tkim135** [comment]
@dcadams looks like it's a matter of migrations again?
screen shot 2018-08-30 at 10 51 58 am

**Comment by dcadams** [comment]
I saw that. Is your branch up-to-date with master?

**Comment by stvstnfrd** [comment]
@dcadams Is this branch worth holding on to?
If so, do you intend on running with it?

**Pull request closed without merging**
