### PR TITLE
Migrates shopping cart button css to forum

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd 

Screenshot (before, with theme):
theme_before

Screenshot (after, with theme):
screen shot 2017-10-31 at 10 06 07 am

Screenshot (before, with NO theme):
plain_before

Screenshot (after, with NO theme):
plain_after

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@caesar2164 The commit message and PR don't explain why this change is being made.

Can you amend the message with some context?

Also, can we make it SOP on theming changes to:
- screenshot before, w/out theming
- screenshot before, _with_ theming
- screenshot after, w/out theming
- screenshot after, _with_ theming

**Comment by caesar2164** [comment]
done

**Comment by caesar2164** [comment]
[Shopping cart display is weird / floats left and overlaps with course display name on /discussion/forum.](https://trello.com/c/YnYTSuOk/207-shopping-cart-display-is-weird-floats-left-and-overlaps-with-course-display-name-on-discussion-forum)

**Comment by stvstnfrd** [comment]
+1

**Pull request merged**
