### PR TITLE
Revert "Move studio dialog code into common"

### PR DESCRIPTION
**Pull request by stvstnfrd**
This reverts commit 36f0617c96ecd5bf5daef45406195b64a4833fe0.

Conflicts:
	lms/djangoapps/teams/templates/teams/teams.html

### CODE REVIEW

**Comment by stvstnfrd** [comment]
This replaces #407

**Comment by stvstnfrd** [comment]
@kluo @caesar2164

**Comment by kluo** [comment]
+1

**Comment by caesar2164** [comment]
cool, :+1:

**Comment by stvstnfrd** [comment]
@dcadams

**Comment by stvstnfrd** [comment]
@azimpradhan

**Pull request merged**
