### PR TITLE
Remove unnecessary fork to contentstore test

### PR DESCRIPTION
**Pull request by stvstnfrd**
This drops the diff down to a single line.

### CODE REVIEW

**Comment by caesar2164** [comment]
Do we not care to display the lockout time?

**Comment by stvstnfrd** [comment]
@caesar2164 I'm not touching the template; this just changes the test to only check for the first sentence.
I'm actually going to send this upstream too.

**Comment by caesar2164** [comment]
DOH, serves me right for not reading fully...

**Comment by stvstnfrd** [comment]
@caesar2164 https://github.com/edx/edx-platform/pull/17502

**Comment by stvstnfrd** [comment]
@caesar2164 I just rebased this.

**Comment by caesar2164** [comment]
cool! 👍

**Pull request merged**
