### PR TITLE
Revert "Merge pull request #287 from Stanford-Online/azimpradhan/sysadmin-course-tabs"

### PR DESCRIPTION
**Pull request by azimpradhan**
This reverts commit 2e65165d2d40ae46e17d845b71e6c31674f22fbc, reversing
changes made to 92893bccc77b9269fb783010b10bbf3b109b8e87.

### CODE REVIEW

**Comment by azimpradhan** [comment]
retest this please

**Comment by azimpradhan** [comment]
@stvstnfrd, @caesar2164, please review. Git revert went pretty smoothly, there were some minor import conflicts which I fixed. The feature is removed from the sysadmin dashboard when running this branch on devstack

**Comment by stvstnfrd** [comment]
@azimpradhan Like #380 this is only failing on the same 2 tests I'm seeing fail on master, so I think you can ignore the failures for now.

**Comment by stvstnfrd** [comment]
+1 from me.

**Pull request merged**
