### PR TITLE
Unfork registration honor marketing link overrides

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd & @kluo - removing marketing link fork from registration pages

### CODE REVIEW

**Comment by stvstnfrd** [comment]
Same questions as the other PR:
- what other diff do we have on these files?
- what command are you using to diff?

**Comment by caesar2164** [comment]
Test this please

**Comment by stvstnfrd** [comment]
retest this please

**Comment by caesar2164** [comment]
retest this please

**Pull request merged**
