### PR TITLE
Fix 'Download Blank Grade Submission CSV button

### PR DESCRIPTION
**Pull request by stvstnfrd**
This was lost in the Coffeescript -> JavaScript transition.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@caesar2164

**Comment by stvstnfrd** [comment]
@caesar2164 Looks like it?

**Comment by stvstnfrd** [comment]
@caesar2164 Or actually, no, not conflict resolution. I think you missed it in porting over our forked changes in the CS file.

**Comment by caesar2164** [comment]
doing what the code above says, results in downloading the CSV file, so 👍

**Pull request merged**
