### PR TITLE
Update options

### PR DESCRIPTION
**Pull request by rachelg4**
@stvstnfrd @dcadams

### CODE REVIEW

**Comment by rachelg4** [comment]
This is replacing my original pull request since I sorted out my branches

**Comment by dcadams** [comment]
Are these two requirements from the trello card still wanted?

--------------------------------------
Make it a required field.
Remove the optional text field that appears when you select the "Other, please enter" option in the "Sub-Specialty" drop down.
--------------------------------------

**Comment by rachelg4** [comment]
One question, some of the previous specialty options had subspecialty menus. Should I try and convert those? For example, one option went from Cardiology to Cardiovascular health.

**Comment by rachelg4** [comment]
Also, currently a text field does not appear when "Other" is entered in specialty, but it is in the html. Should I fix it?

**Comment by rachelg4** [comment]
The affliction logic removed and in #482 , this now only contains specialty option changes. This is blocked pending feedback from CME

**Comment by stvstnfrd** [comment]
Closing in favor of #580

**Pull request closed without merging**
