### PR TITLE
Fix header [revised]

### PR DESCRIPTION
**Pull request by karandikar**
Fixes shopping cart misalignment and vertical centering issues in CME header bar. Replaces PR https://github.com/Stanford-Online/edx-platform/pull/590

@stvstnfrd @caesar2164

### CODE REVIEW

**Comment by stvstnfrd** [comment]
This is _much_ smaller :)

**Comment by caesar2164** [comment]
CSS tricks of the trade ;)

**Comment by caesar2164** [comment]
👍  pending tests and screenshots

**Comment by stvstnfrd** [comment]
Tests look good; @karandikar can you attach the screenshots before we merge?

**Comment by karandikar** [comment]
Before: 
image
After:
image

**Pull request merged**
