### PR TITLE
Fix problem count increment for metrics tab.

### PR DESCRIPTION
**Pull request by dcadams**
Fix problem count increment.

Bug was introduced when adding support for content library problems.

### CODE REVIEW

**Comment by dcadams** [comment]
retest this please

**Comment by stvstnfrd** [comment]
retest this please

**Comment by dcadams** [comment]
retest this please

**Comment by dcadams** [comment]
retest this please

**Comment by dcadams** [comment]
Failing i18n test is nothing to do with this PR.

@kluo can you take a look please.

**Comment by caesar2164** [comment]
👍

**Pull request merged**
