### PR TITLE
Query courseware_studentmodule for metrics if API is not set up

### PR DESCRIPTION
**Pull request by dylanrhodes**
This is a small change to the metrics tab which allows it to query courseware_studentmodule for large classes' data if an API server is not configured.  This is useful for edge cases in which we are running instances that do not have a full analytics backend deployed yet which still have sizable classes (ie. CME).  It should not affect the behavior of the metrics tab on instances with corresponding analytics backends.

It would be helpful if I could get a once over of this PR. @stvstnfrd @dcadams

### CODE REVIEW

**Comment by dcadams** [comment]
I'm ok with the changes, just wondering if we need another 3 tests.

**Comment by dcadams** [comment]
:+1:

**Comment by dylanrhodes** [comment]
@stvstnfrd is there time to get this into the next release?  It's not a large change and would fix some issues on CME.

**Comment by dylanrhodes** [comment]
@stvstnfrd I'm going to go ahead and merge, because the issue with the metrics tab on CME came up again after the most recent deploy, so it seems like we need this in production.

**Pull request merged**
