### PR TITLE
Add port to activation link to keep it from failing on devstack

### PR DESCRIPTION
**Pull request by saharm1**

### CODE REVIEW

**Comment by caesar2164** [comment]
@saharm1 did you perhaps PR this to the wrong branch?

**Comment by saharm1** [comment]
@caesar2164 yes let me close this PR, i made it to edx!

**Comment by stvstnfrd** [comment]
@saharm1 Now that this has merged upstream, we'll want to cherry-pick it from upstream.

You'll want to reset this branch back to origin and then pull in the change, something like:

```sh
git reset --hard origin/master
git cherry-pick 9bfeebe01c49720bc711a2242fa985b9d90582d2
git cherry-pick aa0e1c3786b1b5fe100d24145a26e07f5c823bba
```

Ask if you have questions or want to walk through it together.

**Comment by stvstnfrd** [comment]
No need to close this; just need to update the branch.

**Pull request merged**
