### PR TITLE
Fix broken CMS tests imports for bulk utilities

### PR DESCRIPTION
**Pull request by stvstnfrd**
This was an oversight on my behalf when previously relocating the bulk utility code.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
CC: @dcadams This came up due to the test failures your pointed out on your branch:
- https://github.com/Stanford-Online/edx-platform/pull/892

**Comment by stvstnfrd** [comment]
@tanyaxp Hold off on review here until further notice;
I'm still working out some test issues.

**Comment by stvstnfrd** [comment]
@tanyaxp Okay, this is ready for eyes now.

@dcadams Do you mind taking a look, since you've been part of this work too (test infrastructure)?

**Comment by dcadams** [comment]
:+1:

**Pull request merged**
