### PR TITLE
[WIP] Remove old cme_registration integration points

### PR DESCRIPTION
**Pull request by stvstnfrd**
The app itself is still in place for now, but the integration points are
cut off.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
Consider this a more pressing subset of https://github.com/Stanford-Online/edx-platform/pull/744

**Comment by dcadams** [comment]
I don't understand why this is pressing if it is WIP and failing relevant tests.

**Comment by stvstnfrd** [comment]
@dcadams Look at the timeline: it was marked as WIP _after_ that comment.

**Comment by stvstnfrd** [comment]
@dcadams Sorry for the confusion.

**Comment by stvstnfrd** [comment]
@dcadams I was hoping I could tease out part of #744 , but that's looking to be problematic with the test suite. Let's just ignore this and instead focus on #744

**Pull request closed without merging**
