### PR TITLE
Install "Submit and Compare" XBlock

### PR DESCRIPTION
**Pull request by stvstnfrd**

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@jbau @caesar2164 @dcadams

**Comment by dcadams** [comment]
:+1: pending Jenkins.

**Comment by stvstnfrd** [comment]
FYI @jinpa 

Per F2F discussion, Ross has requested that we hold off on releasing this; he found a bug to fix first. We'll add this to the next release following Ross' go-ahead.

**Comment by stvstnfrd** [comment]
@jinpa says "ship it!"

**Comment by stvstnfrd** [comment]
This is working on stage, so I'll hit the button.

**Pull request merged**
