### PR TITLE
Giulio/revert account name

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd, @kluo - here's a revert or all the ACCOUNT_NAME stuff...

### CODE REVIEW

**Comment by stvstnfrd** [comment]
I don't see any matches when I grep for `ACCOUNT_NAME` so this LGTM if tests are OK.

Can you remove the relevant entries from config/secure?

**Comment by caesar2164** [comment]
done.

**Comment by kluo** [comment]
Also need to remove the custom translations in https://github.com/Stanford-Online/lagunita-theme/blob/master/conf/locale/es_419/LC_MESSAGES/django.po that reference account_name

**Comment by caesar2164** [comment]
good catch, @kluo, what should i replace the translations with?

**Comment by caesar2164** [comment]
translation changes made in lagunita theme: https://github.com/Stanford-Online/lagunita-theme/pull/31

**Pull request merged**
