### PR TITLE
Adding missing migration.

### PR DESCRIPTION
**Pull request by caijim**
Without this, devstack is broken because it complains
about missing migrations for course_groups.

### CODE REVIEW

**Comment by jbau** [comment]
retest this please

**Comment by jbau** [comment]
did you create the migrations directly from south?

this PR seems fine, now that the tests pass.

**Comment by caijim** [comment]
Yea, I just ran the automatic generation command and did some minor PEP8
spacing changes

**Comment by jbau** [comment]
OK.  One last thing I'd like to confirm before this merges is that it will work properly on prod-like envs.  It can always be a bit weird to add initial migrations after the fact, so I want to figure out if we need to fake these migrations on stage/prod.

**Comment by caijim** [comment]
What would be the way to test this/ find this out? At this point, I am ok with leaving this here until someone else runs into the same problem (and if stage/prod are working there's not really a reason to add this now)

**Comment by jbau** [comment]
Oh, I don't mean for you to test it. =)  we'll just have to try it on stage.

**Comment by stvstnfrd** [comment]
@caijim What did we ever find out about this? Do we need this or no?

**Comment by caijim** [comment]
No one seems to be having a problem with this anymore. Closing it

**Comment by stvstnfrd** [comment]
Hey @caijim I just ran into this on stage. I have some ideas on what caused it, but I'd like to put heads together on this tomorrow if you'll be in.

**Pull request closed without merging**
