### PR TITLE
Fixed off-center fullscreen video captions

### PR DESCRIPTION
**Pull request by axelsly**
@stvstnfrd @caesar2164 @caseylitton 

Fixed CSS for video-wrapper to center closed captions (CC) with scrolling side captions enabled.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@stanford-online-robot Yes, I can verify this patch.

**Comment by stvstnfrd** [comment]
test this please

**Comment by stvstnfrd** [comment]
test this please

**Comment by caesar2164** [comment]
@axelsly can you show me this working when you're in the office next?

**Comment by stvstnfrd** [comment]
> @axelsly can you show me this working when you're in the office next?

@caesar2164 I think people have started falling away from this, but you really should be running this locally yourself in an origin devstack.

By relying on Axel to demo, we risk missing whole classes of issues.
The most common form of this is when a developer forgets to check in a file to git;
it works perfectly for them but would fall over flat on anyone else's system.

**Comment by caesar2164** [comment]
confirmed that the fix works, but I'm not too keen on forking this. Maybe we make the change in theme? @stvstnfrd ?

**Comment by stvstnfrd** [comment]
@caesar2164 Is this a bug on upstream?
If so, let's fix it here and push it upstream.

If not, then we need to find out which of our styling rules is throwing this off and necessitating the fix in the first place.

**Comment by caesar2164** [comment]
doh! https://github.com/edx/edx-platform/pull/12676

we're getting a fix for this for free in merge...

**Comment by stvstnfrd** [comment]
@caesar2164 FWIW: that commit applies cleanly into our master;
should we cherry-pick it?

**Comment by axelsly** [comment]
@stvstnfrd @caesar2164 
Cherry-picked the changes from upstream

**Comment by caesar2164** [comment]
this looks pretty good to me 👍

**Comment by stvstnfrd** [comment]
+1

**Pull request merged**
