### PR TITLE
Fix ORA2 drafts

### PR DESCRIPTION
**Pull request by stvstnfrd**

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@caesar2164 I'm running tests locally now.

**Comment by caesar2164** [comment]
ok

**Comment by caesar2164** [comment]
[Attempting to discard changes in a unit with ORA2 results in unit updating to say "Draft saved on X date at X time by <current user>."](https://trello.com/c/6f4HqNNU/192-attempting-to-discard-changes-in-a-unit-with-ora2-results-in-unit-updating-to-say-draft-saved-on-x-date-at-x-time-by-current-use)

**Comment by stvstnfrd** [comment]
retest this please

**Pull request merged**
