### PR TITLE
Install Stanford UX Pattern Library from master

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd 

now that this is merged to master, we need to install from master

Keeping branch in that repo until we merge this PR, then we should delete the branch here: https://github.com/Stanford-Online/ux-pattern-library/pull/1

### CODE REVIEW

**Comment by caesar2164** [comment]
[add Stanford edx-pattern-library npm install to our deploy procedures](https://trello.com/c/RoZd5AIv/131-add-stanford-edx-pattern-library-npm-install-to-our-deploy-procedures)

**Comment by stvstnfrd** [comment]
+1 after tests

**Comment by stvstnfrd** [comment]
+1 after tests

**Comment by stvstnfrd** [comment]
retest this please

**Pull request merged**
