### PR TITLE
Update to version 0.1.4 of in-video-quiz

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd & @kluo

### CODE REVIEW

**Comment by kluo** [comment]
Amazing! +1

**Comment by caesar2164** [comment]
retest this please

**Comment by stvstnfrd** [comment]
@caesar2164 I think this needs rebased?

**Comment by caesar2164** [comment]
@stvstnfrd just did ^

**Comment by caseylitton** [comment]
retest this please

**Comment by caseylitton** [comment]
+1

**Pull request merged**
