### PR TITLE
Remove merge artifacts

### PR DESCRIPTION
**Pull request by stvstnfrd**
These were mistakenly left in place after the upstream merge. Each line
was commented out, however, so this should have no effect on behavior.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@dcadams

**Comment by dcadams** [comment]
Let's not do this for now until we've sorted out the cause of the issue.

**Comment by stvstnfrd** [comment]
I'm in no rush, just wanted to put it up there before I forgot.

**Comment by stvstnfrd** [comment]
I remove these in an upcoming commit.

**Pull request closed without merging**
