### PR TITLE
Layout structure for community contributions

### PR DESCRIPTION
**Pull request by stvstnfrd**
We should strive to place as much of our code within this module
(modeled after `django.contrib` and `openedx.core`).

This will reduce the amount of forking we need to do within existing
files.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@dcadams @caesar2164 @kluo I've been pondering this approach for a bit and wanted to open a dialogue about how to best isolate our changes from the core of the OpenEdX codebase.

**Comment by stvstnfrd** [comment]
I had originally reworked our use of `django.conf.settings` to split our customized `setting`s out into a separate directory in #346 . Instead, I'll port that over here.

**Comment by caesar2164** [comment]
hmm, why the test failure?

**Comment by stvstnfrd** [comment]
@caesar2164 Those are all unrelated failures caused by the `test_root` directory. I just merged my fix and will rebase this on top of it.

**Comment by stvstnfrd** [comment]
Actually, @albertliangcode is going to be putting some code over here, so I'm going to go ahead and merge this for now. I'll add the settings refactor to a separate PR.

**Comment by caesar2164** [comment]
I like this idea! :+1:

**Comment by stvstnfrd** [comment]
I still like this idea, though this PR doesn't really offer much. Closing for now..

**Pull request closed without merging**
