### PR TITLE
Put enrollment email behind feature flag

### PR DESCRIPTION
**Pull request by kluo**
@caesar2164

### CODE REVIEW

**Comment by caesar2164** [comment]
WOOHOO! :+1:

**Comment by kluo** [comment]
retest this please

**Comment by kluo** [comment]
retest this please

**Comment by kluo** [comment]
retest this please

**Comment by kluo** [comment]
retest this please

**Comment by stvstnfrd** [comment]
Hrmm.... I got a clean build manually [1].

I'm not sure what's going on...

[1] https://jenkins.class.stanford.edu:8080/job/Stanford_Online_Unit_Tests_auto_pr/667/console

**Comment by stvstnfrd** [comment]
retest this please

**Comment by kluo** [comment]
at last!

**Pull request merged**
