### PR TITLE
Allow hiding of discussion tab in CMS

### PR DESCRIPTION
**Pull request by stvstnfrd**

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@dcadams It looks like this was added to the platform, but no corresponding entry was added to `configuration`. Luckily for us, we want it enabled across the board, so we can just do it here.

**Comment by stvstnfrd** [comment]
this this please

**Comment by stvstnfrd** [comment]
test this please

**Comment by dcadams** [comment]
retest this please

**Comment by dcadams** [comment]
:+1:

**Pull request merged**
