### PR TITLE
Added a new setting for ACCOUNT_NAME.

### PR DESCRIPTION
**Pull request by lydiali**
- ACCOUNT_NAME : Stanford Online

@caesar2164 @stvstnfrd

### CODE REVIEW

**Comment by caesar2164** [comment]
seems reasonable to me, @stvstnfrd ?

**Comment by caesar2164** [comment]
before this is merged, you should rebase, @lydiali

**Comment by stvstnfrd** [comment]
Where are we passing `ACCOUNT_NAME` to the context for the email `.txt` file templates?

**Comment by stvstnfrd** [comment]
Makes sense, but is there a corresponding PR to secrets? (don't include the link here; PM me ;))

**Comment by stvstnfrd** [comment]
Closing, we cherry-picked this into the RC

**Pull request closed without merging**
