### PR TITLE
Rename student submissions reports to responses reports

### PR DESCRIPTION
**Pull request by kluo**
This is to avoid confusion with the existing edx-submissions
repo.

@dcadams @jbau

### CODE REVIEW

**Comment by stvstnfrd** [comment]
This seems reasonable, though I'd like a +1 from @dcadams , since this is related to his work.

Will this require any messaging/explanation for instructors? cc @gbruhns 

Since the CSV filename is being changed, could this break any external dependencies? Are there any tools or automated processes which depend on this?

**Comment by jbau** [comment]
looks fine to me +1

**Comment by kluo** [comment]
@stv there aren't any external dependencies on the filename, so it should be ok.

**Comment by dcadams** [comment]
LGTM.

**Comment by stvstnfrd** [comment]
+1

**Pull request merged**
