### PR TITLE
Fix broken CME registration tests

### PR DESCRIPTION
**Pull request by dcadams**
Need to reset urls for these tests since edx made this part of the urls conditional.

### CODE REVIEW

**Comment by dcadams** [comment]
@stvstnfrd please.

**Comment by stvstnfrd** [comment]
Thanks @dcadams  . I've cherry-picked and pushed. I'll close and delete the branch once the tests pass on my end.

**Comment by stvstnfrd** [comment]
Hey @dcadams . While this patch does correct the failing CME tests, it looks like it introduces some new JavaScript failures. @kluo confirmed that these fail with the patch, but succeed upon reverting this commit.

```
Cohorts View: can show discussion topics if cohort exists [fail]
    TypeError: CourseWideDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/groups/views/cohorts.js (line 292)

Cohorts View Discussion Topics: renders the view properly [fail]
    TypeError: CourseWideDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/groups/views/cohorts.js (line 292)

Cohorts View Discussion Topics Course Wide: shows the "Save" button as disabled initially [fail]
    TypeError: CohortCourseWideDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1085)

Cohorts View Discussion Topics Course Wide: has one cohorted and one non-cohorted topic [fail]
    TypeError: CohortCourseWideDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1085)

Cohorts View Discussion Topics Course Wide: enables the "Save" button after changing checkbox [fail]
    TypeError: CohortCourseWideDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1085)

Cohorts View Discussion Topics Course Wide: saves the topic successfully [fail]
    TypeError: CohortCourseWideDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1085)

Cohorts View Discussion Topics Course Wide: shows an appropriate message when subsequent "GET" returns HTTP500 [fail]
    TypeError: CohortCourseWideDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1085)

Cohorts View Discussion Topics Course Wide: shows an appropriate error message for HTTP500 [fail]
    TypeError: CohortCourseWideDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1085)

Cohorts View Discussion Topics Inline: shows the "Save" button as disabled initially [fail]
    TypeError: CohortInlineDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1096)

Cohorts View Discussion Topics Inline: shows always cohort radio button as selected [fail]
    TypeError: CohortInlineDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1096)

Cohorts View Discussion Topics Inline: shows cohort some topics radio button as selected [fail]
    TypeError: CohortInlineDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1096)

Cohorts View Discussion Topics Inline: has cohorted and non-cohorted topics [fail]
    TypeError: CohortInlineDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1096)

Cohorts View Discussion Topics Inline: enables "Save" button after changing from always inline option [fail]
    TypeError: CohortInlineDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1096)

Cohorts View Discussion Topics Inline: saves the topic [fail]
    TypeError: CohortInlineDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1096)

Cohorts View Discussion Topics Inline: selects the parent category when all children are selected [fail]
    TypeError: CohortInlineDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1096)

Cohorts View Discussion Topics Inline: selects/deselects all children when a parent category is selected/deselected [fail]
    TypeError: CohortInlineDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1096)

Cohorts View Discussion Topics Inline: saves correctly when a subset of topics are selected within a category [fail]
    TypeError: CohortInlineDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1096)

Cohorts View Discussion Topics Inline: saves correctly when all child topics are selected within a category [fail]
    TypeError: CohortInlineDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1096)

Cohorts View Discussion Topics Inline: shows an appropriate message when no inline topics exist [fail]
    TypeError: CohortInlineDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1096)

Cohorts View Discussion Topics Inline: shows an appropriate message when subsequent "GET" returns HTTP500 [fail]
    TypeError: CohortInlineDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1096)

Cohorts View Discussion Topics Inline: shows an appropriate error message for HTTP500 [fail]
    TypeError: CohortInlineDiscussionsView is not a constructor in http://0.0.0.0:59416/suite/lms/include/js/spec/groups/views/cohorts_spec.js (line 1096)

```

**Comment by dcadams** [comment]
I shall run through the office naked if my change broke these tests.

**Pull request closed without merging**
