### PR TITLE
Short circuits end date description

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd, tested locally and works.

### CODE REVIEW

**Comment by caesar2164** [comment]
[Cert reference appears for non-cert courses with end dates](https://trello.com/c/EyCaCQma/1024-cert-reference-appears-for-non-cert-courses-with-end-dates)

**Comment by stvstnfrd** [comment]
@caesar2164 Tests are legitimately failing due to this change.

We should use a proper feature flag after all.
We can probably enable our new flag by default (show empty string)
and then can just override via `tests.py`.

**Comment by stvstnfrd** [comment]
retest this please

**Comment by caesar2164** [comment]
test this please

**Comment by stvstnfrd** [comment]
@caesar2164 Tests are finally passing, but I noticed we're modifying the main settings file, instead of putting this in our forked files, `openedx/stanford/lms/envs`;
we should do that.

**Comment by caesar2164** [comment]
test this please

**Pull request merged**
