### PR TITLE
Fix sneak peek for hidden content and release dates

### PR DESCRIPTION
**Pull request by stvstnfrd**

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@caesar2164 This seemed to work locally, but could stand to be thoroughly checked on stage.

**Comment by stvstnfrd** [comment]
@caesar2164 and @dcadams 

Tests are passing now; please review.

**Comment by dcadams** [comment]
:+1:

**Comment by caesar2164** [comment]
nice, :+1:

**Pull request merged**
