### PR TITLE
Update SHA of qualtrics XBlock

### PR DESCRIPTION
**Pull request by caesar2164**
- link is now styled like a button

@stvstnfrd & @dcadams

### CODE REVIEW

**Comment by stvstnfrd** [comment]
While functionally equivalent, I'd prefer we point directly to the tip of `master` [1], instead of needing to figure out which is the most recent non-merge commit.

Here, for example, when I wanted to make sure this SHA was correct, I just ran
```sh
git rev-parse origin/master
```

and it tells me where `origin/master` currently points.

To verify this as is, I need to actually inspect the git log and filter out merge commits to be sure we're using the proper value.

[1] 701788bd1a81ef6d97dd5ef6b5c35998266c62a5

**Comment by caesar2164** [comment]
there you go, @stvstnfrd

**Comment by stvstnfrd** [comment]
+1

**Comment by dcadams** [comment]
:+1:

**Pull request merged**
