### PR TITLE
Fix CSS of shopping cart

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd - fixes for shopping-cart styling

### CODE REVIEW

**Comment by caesar2164** [comment]
Before:
screen shot 2017-10-27 at 12 55 32 pm

**Comment by caesar2164** [comment]
After:
screen shot 2017-10-27 at 2 11 40 pm

**Comment by caesar2164** [comment]
[Shopping cart things that might need tending before we release to prod.](https://trello.com/c/WDTNkdls/205-shopping-cart-things-that-might-need-tending-before-we-release-to-prod)

**Comment by stvstnfrd** [comment]
+1

**Comment by mondiaz** [comment]
👍 unless Lydia says otherwise in Slack. In any case, if there's push back about the lack of dates in that one location, we can add that as a card to work on after the merge, so this looks good to me at this time. Thanks!

**Comment by caesar2164** [comment]
test this please

**Comment by stvstnfrd** [comment]
retest this please

**Pull request merged**
