### PR TITLE
Fix styling of sneak peek ToS footer

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd edited unauth-tos and made the selector more specific

### CODE REVIEW

**Comment by caesar2164** [comment]
Before:
screen shot 2016-12-16 at 11 13 05 am

After:
screen shot 2016-12-16 at 11 12 50 am

**Comment by caesar2164** [comment]
@Stanford-Online/openedx-courseops

**Comment by mondiaz** [comment]
@caesar2164 lgtm!

**Comment by gbruhns** [comment]
LGTM! Thanks!!

**Pull request merged**
