### PR TITLE
Makes copyright link in footer work

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd adding copyright to common.py

### CODE REVIEW

**Comment by caesar2164** [comment]
[Inconsistent messaging on TOS/PP/HONOR pages](https://trello.com/c/hhvqvMb9/166-inconsistent-messaging-on-tos-pp-honor-pages)

**Comment by caesar2164** [comment]
[Copyright link in footer doesn't do anything...](https://trello.com/c/UYsAXdIE/96-copyright-link-in-footer-doesnt-do-anything)

**Comment by stvstnfrd** [comment]
+1

**Comment by caesar2164** [comment]
test this please

**Pull request merged**
