### PR TITLE
Fix script statement order, query filter, and improve output

### PR DESCRIPTION
**Pull request by kluo**
@stvstnfrd @dcadams

### CODE REVIEW

**Comment by stvstnfrd** [comment]
Why change order?

**Comment by dcadams** [comment]
Hasn't this script already been run, and verified, on stage? What's the reason to change it now? How do we test it again?

**Comment by kluo** [comment]
I had to make these additional changes for the script to successfully run. The reason is the previous order of fetching the submission from the preceding score AFTER just creating a new override score was incorrect.

**Comment by dcadams** [comment]
Oh, so the migration <did> run on stage with this code. This is just an update ex post facto.

**Pull request merged**
