### PR TITLE
Hide overflow of component ID in studio

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd & @kluo

### CODE REVIEW

**Comment by stvstnfrd** [comment]
It's a bit hard to tell what really changed without a "before" shot :)

Was it the location id that would overflow?

What about `ellipsis`?

**Comment by caesar2164** [comment]
new screenshot:

screen shot 2016-08-19 at 10 28 41 am

**Comment by stvstnfrd** [comment]
+1

**Comment by kluo** [comment]
+1

**Pull request merged**
