### PR TITLE
Plug-in for Data Download/Reports

### PR DESCRIPTION
**Pull request by albertliangcode**

### CODE REVIEW

**Comment by stvstnfrd** [comment]
Great @albertliangcode !

Remember how we intentionally decided on this iterative implementation
plan so tests still pass and everything still works?
That means we can pause and defer on `get_module_for_student_method` for
now and revisit the decision once more of the infrastructure shakes
out. That's a flexibility afforded to us by choosing this approach.

Of course, let's double-check what is/isn't upstream, but as long as we
have only moved forked/origin code for now, I think we can move onto
other areas.

```shell
git diff origin/aliang8/report..origin/diff/upstream lms/djangoapps/instructor/utils.py
```

I like that you already started splitting the code out into logical
groups/files to add some more clarity. I was thinking we could
extend this even further, something like:

```
openedx.contrib.stanford.data_downloads
├── __init__.py
├── reports
│   ├── __init__.py
│   ├── ora2_anonymous.py
│   └── ora2_email.py
└── util.py
```

The idea is that each report should have its own module/file
inside of `reports`, with any shared logic moving into `util.py`.

Take a look at what I've pushed onto your branch and let me know what
you think.

**Comment by stvstnfrd** [comment]
Once we've split things out such that there's one file per report, we
should start tracing back up a layer. Instead of importing the methods
implicitly via `import` statements in `lms/djangoapps/instructor/utils.py`,
let's find the files that are importing from
`lms/djangoapps/instructor/utils.py` and update them to instead import
directly from `openedx.contrib.stanford.data_download.reports.whatever`.

**Comment by albertliangcode** [comment]
Sounds awesome!  I'll move everything into its place, and get started redirecting imports to pull directly from the new locations instead.

Just to make sure, let me sketch out what I'm thinking just to make sure I'm on the same page as you:

**Comment by albertliangcode** [comment]
```
Old instructors/utils.py
Methods and their Dependencies within the file:


get_module_for_student
  |                             
  +-> Dummy_Request


collect_course_forums_data          
  |
  +-> merge_join_course_forums        


collect_student_forums_data          
  |
  +-> generate_student_forums_query                     


collect_anonymous_ora2_data          
  |
  +------------------------+
                           |
collect_email_ora2_data    |
            |              |
            +--------------+-> collect_ora2_data
                                 |
                                 |
                                 +-> ora2_data_queries
                                     *This is the one I moved 1st





contrib/stanford/datadownload
New Structure:

openedx.contrib.stanford.data_downloads
├── __init__.py
├── reports
│   ├── __init__.py
│   ├── ora2_anonymous.py
|   |       *collect_anonymous_ora2_data
│   |── ora2_email.py
|   |       *collect_email_ora2_data
|   |–– forums_course.py
|   |       *collect_student_forums_data
|   |       *merge_join_course_forums
|   |       *generate_course_forums_query
|   +–– forums_students.py
|           *collect_student_forums_data
|           *generate_student_forums_query
└── util.py
        *collect_ora2_dta
        *ora2_data_queries
```

**Comment by albertliangcode** [comment]
@stvstnfrd: Is this what you're thinking?

**Comment by stvstnfrd** [comment]
Yup, exactly! Thanks for drawing that out; it's exactly what I had in
mind.

From there, if any of those methods are only ever referenced from the
same file ("local", for all intents and purposes; you'll have to grep
around, but maybe `generate_*`, `merge_*`), we can mark them as
"private" by prepending an underscore `_` to the name. This will
increase clarity about what methods are being exposed and which are
internal helpers.

The same idea can be applied to local, module-level variables.

**Comment by albertliangcode** [comment]
Okay!  I'll get started right now!

**Comment by albertliangcode** [comment]
retest this please

**Comment by albertliangcode** [comment]
retest this please

**Comment by albertliangcode** [comment]
retest this please

**Comment by albertliangcode** [comment]
retest this please

**Comment by albertliangcode** [comment]
retest this please

**Comment by stvstnfrd** [comment]
Closing for now due to large number of conflicts.

**Pull request closed without merging**
