### PR TITLE
Fix recursive template lookup

### PR DESCRIPTION
**Pull request by caseylitton**
@stvstnfrd @kluo @dcadams @caesar2164 This is a PR to fix a recursive html template file look up issue.  This issue occurs if you try to inherit a 'base' template html file from a themed template file.

lms.env.json
COMPREHENSIVE_THEME_DIRS: ["/edx/app/edxapp/themes/sample-themes"]
DEFAULT_SITE_THEME: "test-partial-stanford-theme"
ENABLE_COMPREHENSIVE_THEMING": true

At the same level as edx-platform, there needs to be a themes/sample-themes/test-partial-stanford-theme folder.  test-partial-stanford-theme has a specific structure... lms/static/{css,images,js,sass}/ and lms/tempaltes

### CODE REVIEW

**Comment by caesar2164** [comment]
you should fix the commit name... 😉

**Comment by mtyaka** [comment]
Hey @caesar2164, I believe you showed me this PR at the Open edX conference. I tested it and it seems to work great!

Would you (or somebody from your team) be willing to contribute this patch upstream? I would be more than happy to help get this merged. I can help you test, perform a formal code review, and nag upstream about it :)

If you add some tests, and describe the problem that it solves and how it solves it (it's not immediately obvious looking at the code) in the PR description and/or code comments, I don't see any reason why this wouldn't get merged.

**Comment by caesar2164** [comment]
@stvstnfrd & @caseylitton see comment above!

**Comment by mtyaka** [comment]
@stvstnfrd @caseylitton @caesar2164 ping :)

**Pull request closed without merging**
