### PR TITLE
Add Grade Me XBlock

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd - this one is a plain commit and not a revert, as the SHA changed...

### CODE REVIEW

**Comment by stvstnfrd** [comment]
Test this please.

**Comment by mondiaz** [comment]
+1 :+1:

**Comment by caesar2164** [comment]
retest this please.

**Comment by stvstnfrd** [comment]
I'm not seeing a PR on the GradeMe Button repo..?

**Comment by caesar2164** [comment]
@stvstnfrd it's just using the master branch...

**Comment by stvstnfrd** [comment]
> it's just using the master branch...

We really need to stop this practice. 

We _need_ to be tagging releases.

Since this is an installable Python package, we should be taking advantage of `setup.py`'s version number metadata; Semantic Versioning [1] is probably our best bet here.

Further, we should just publish this to PyPi and not even install via Github.

Maybe we can walk through this today as a precursor to you shadowing the install process?

[1] http://semver.org/

**Pull request merged**
