### PR TITLE
Unfork whitespace

### PR DESCRIPTION
**Pull request by stvstnfrd**

### CODE REVIEW

**Comment by stvstnfrd** [comment]
`lms/djangoapps/bulk_email/tasks.py` is now identical to `ficus.master`.

**Comment by stvstnfrd** [comment]
retest this please

**Comment by stvstnfrd** [comment]
retest this please

**Comment by stvstnfrd** [comment]
retest this please

**Comment by stvstnfrd** [comment]
@caesar2164 I keep getting the `gitlog_pagination error`.
Can you confirm and are you okay w/ just merging this?

**Comment by caesar2164** [comment]
I'm ok with merging in spite of gitlog error.

**Pull request merged**
