### PR TITLE
Allow CME registration to accept Fed 29 birthdays

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd & @dcadams - it was literally a 1 character fix...

### CODE REVIEW

**Comment by dcadams** [comment]
What's up with Jenkins?

**Comment by caesar2164** [comment]
@dcadams how's that?

**Comment by dcadams** [comment]
How about also changing the date in the test file:
'birth_date': '09/24',

**Comment by caesar2164** [comment]
sure, but why 09/24?

**Comment by dcadams** [comment]
That's what it is right now. How about changing it to 02/29.

**Comment by caesar2164** [comment]
ah, that makes sense!

**Comment by caesar2164** [comment]
@dcadams - tada!

**Comment by stvstnfrd** [comment]
+1

Good call on the test change @dcadams

**Comment by dcadams** [comment]
:+1: pending tests

**Pull request merged**
