### PR TITLE
Fix of course tiles after upstream merge.

### PR DESCRIPTION
**Pull request by dcadams**
Basically fixes a merge issue, not really any new logic.

### CODE REVIEW

**Comment by dcadams** [comment]
@stvstnfrd

**Comment by dcadams** [comment]
This should fix the course tile sorting issue on Stage.

**Comment by stvstnfrd** [comment]
Thanks for the updated fix, @dcadams ! I've gone ahead and cherry-picked this commit.

**Comment by dcadams** [comment]
Cherry-picked, checked, all ok so closing.

**Pull request closed without merging**
