### PR TITLE
Initialize settings in xmodule_asset main() function

### PR DESCRIPTION
**Pull request by caesar2164**
TNL-3612

I'm not sure this is the best fix for this problem...

@stvstnfrd - cherry pick a fix ned made!

### CODE REVIEW

**Comment by caesar2164** [comment]
@kluo - you too so you can put this on stage!

**Comment by stvstnfrd** [comment]
> I'm not sure this is the best fix for this problem...

Please explain.

**Comment by caesar2164** [comment]
the message is straight from ned's PR

**Comment by caesar2164** [comment]
https://github.com/edx/edx-platform/pull/10199

**Comment by stvstnfrd** [comment]
Seems reasonable.

**Comment by kluo** [comment]
+1

**Pull request merged**
