### PR TITLE
Updated SHA of xblock-submit-and-compare

### PR DESCRIPTION
**Pull request by azimpradhan**

### CODE REVIEW

**Comment by caesar2164** [comment]
:+1:

**Comment by caesar2164** [comment]
@stvstnfrd

**Comment by azimpradhan** [comment]
@stvstnfrd, the grading feature has also been PRed upstream:
https://github.com/openlearninginitiative/xblock-submit-and-compare/pull/3

**Comment by stvstnfrd** [comment]
+1

**Pull request merged**
