### PR TITLE
Change course navigation z-index

### PR DESCRIPTION
**Pull request by karandikar**
Fixes issue with header drop-down appearing below course
navigation bar on page. @stvstnfrd @caesar2164

### CODE REVIEW

**Comment by caesar2164** [comment]
@karandikar, can we get a screenshot of this fixing both issues?

**Comment by karandikar** [comment]
**Before**:
Student:
image
Staff: (I deleted the course nav bar so the issue would be apparent)
image

**After**:
Student:
image
Staff: (I deleted the course nav bar so the issue would be apparent)
image

**Comment by stvstnfrd** [comment]
+1

**Comment by caesar2164** [comment]
👍

**Pull request merged**
