### PR TITLE
UI changes and set max_attempts to unlimited/None

### PR DESCRIPTION
**Pull request by tanyaxp**
UI changes and set max_attempts to unlimited/None when the user
selects zero

### CODE REVIEW

**Comment by tanyaxp** [comment]
@stvstnfrd , @caesar2164 Please review these changes.

Thanks
Tanya

**Comment by tanyaxp** [comment]
@stvstnfrd Please take a look. Thanks Tanya

**Comment by stvstnfrd** [comment]
@tanyaP is the `max_attempts == 0/None` issue sorted out now? and have we shown that to @jen-nifer ?

**Comment by tanyaxp** [comment]
@stvstnfrd I have fixed the max_attempts == 0/None issue and I reviewed it with @jen-nifer, Monica and Kailey yesterday. I had introduced a new bug to the advanced settings and fixed that as well yesterday afternoon.

**Pull request merged**
