### PR TITLE
Fix an incomplete merge for the account settings fields

### PR DESCRIPTION
**Pull request by kluo**
@stvstnfrd @caesar2164

### CODE REVIEW

**Comment by caesar2164** [comment]
As long as it runs locally and passes tests, 👍

**Comment by stvstnfrd** [comment]
+1, worked for me locally in a new devstack.

**Comment by caesar2164** [comment]
great! 👍

**Comment by caesar2164** [comment]
[Account setting fields duplicate](https://trello.com/c/qHiHDlhF/168-account-setting-fields-duplicate)

**Pull request merged**
